# About Quiz 3 ...

In [ ]:
import numpy as np

Let's make our translation matrix

In [ ]:
translate = np.array([[1, 0, -10], [0, 1, 25], [0, 0, 1]])
print(translate)

Let's make our scale matrix

In [ ]:
scale = np.array([[2, 0, 0], [0, .5, 0], [0, 0, 1]])
print(scale)

What happens when we multiply them in this order?

In [ ]:
translate@scale

What happens when we multiply them in this order?

In [ ]:
scale@translate

Alright, let's make some data

In [ ]:
data = np.array([[10, 4, 1], [20, 2, 1]])
print(data)

If I translate my data...

In [ ]:
(translate@data.T).T

If I scale my data...

In [ ]:
(scale@data.T).T

If I translate then scale then transform my data...

In [ ]:
((translate@scale)@data.T).T

If I scale then translate then transform my data...

In [ ]:
print(data)
((scale@translate)@data.T).T

So matrix multiplication is **associative** but not **commutative**:
* (A@B)@C = A@(B@C) but
* A@B != B@A

Which order do you think is a better interpretation of the question in the quiz?

Take home message: **know the order in which you want your transformations done**.

# About Homework 3

Generally, people seem to know how to set up a transformation matrix:
* translation
* scaling
* rotation in 2D
* rotation in 3D
* max-min normalization

The problem seems to come in actually doing the matrix multiply.

Here's a mnemonic that may help you: Pirates say Argh over the Seas (R over C, rows over columns).

Here's a nice little refresher: https://www.mathsisfun.com/algebra/matrix-multiplying.html.

And here we implement matrix multiply using for loops.

In [ ]:
def matrix_multiply_slowly(m1, m2):
    if m1.shape[1] != m2.shape[0]:
        print("Can't multiply a ", m1.shape, " matrix by a ", m2.shape, " matrix.")
        return None
    res = []
    # rows
    for rowIndex in range(m1.shape[0]):
        # over
        res.append([])
        # columns
        for colIndex in range(m2.shape[1]):
            res[-1].append(dot_product_slowly(rowIndex, colIndex, m1[rowIndex], m2[:,colIndex]))
    return np.array(res)

def dot_product_slowly(i, j, v1, v2):
    if len(v1) != len(v2):
        print("Can't multiply a vector of length ", len(v1), " with a vector of length ", len(v2), ".")
        return 0
    pairs = list(zip(v1, v2))
    print(i, ' ', j, '\t', ' + '.join(['%s*%s'%(i, j) for i, j in pairs]), '\t', np.sum([i*j for i, j in pairs]))
    # sum up the pairwise products
    return np.sum([i*j for i, j in pairs])


In [ ]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[2,0],[0,3]])
print(m1@m2)

In [ ]:
print(matrix_multiply_slowly(m1, m2))

### Translate [[1 2 1] [3 7 3] [4 5 4]] to the origin along the y and z dimensions.

In [ ]:
data = np.array([[1,2,1],[3,7,3],[4,5,4]])

# add trailing 1s for translation
# there is NO NEED to add a bottom row to make the matrix square
homogenizedData = np.append(data, np.array([np.ones(data.shape[0], dtype=int)]).T, axis=1)

# transformation matrix
transform = ??
print(homogenizedData)
print(transform)

In [ ]:
print(matrix_multiply_slowly(transform, homogenizedData.T).T)

### Scale [[1 2 1] [3 7 3] [4 5 4]] by 2 along the x dimension and .5 along the y dimension.

In [ ]:
# we are only scaling so we don't NEED to add the homogenous coordinate; but if you did I gave you credit
transform = ??
print(transform)

In [ ]:
print(matrix_multiply_slowly(transform, data.T).T)

### Perform a local max-min normalization of [[1 2 1] [3 7 3] [4 5 4]].

In [141]:
# transformation matrix
scale = ??
translate = ??
print(rotate)
print(translate)
# remember what we just learned: order matters! we want to scale the effect of the translation, so we pass the scaling through the translation
# also notice if you do it the other way around we do not get a matrix where every value is between 0 and 1
transform = scale@translate
print(transform)

[[ 6.123234e-17  0.000000e+00  1.000000e+00  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00]
 [-1.000000e+00  0.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[ 1  0  0 -1]
 [ 0  1  0 -2]
 [ 0  0  1 -1]
 [ 0  0  0  1]]
[[ 0.33333333  0.          0.         -0.33333333]
 [ 0.          0.2         0.         -0.4       ]
 [ 0.          0.          0.33333333 -0.33333333]
 [ 0.          0.          0.          1.        ]]


In [142]:
# max-min means translation AND scaling, so we need that trailing column of ones
print(matrix_multiply_slowly(transform, homogenizedData.T).T)

0   0 	 0.3333333333333333*1 + 0.0*2 + 0.0*1 + -0.3333333333333333*1 	 0.0
0   1 	 0.3333333333333333*3 + 0.0*7 + 0.0*3 + -0.3333333333333333*1 	 0.6666666666666667
0   2 	 0.3333333333333333*4 + 0.0*5 + 0.0*4 + -0.3333333333333333*1 	 1.0
1   0 	 0.0*1 + 0.2*2 + 0.0*1 + -0.4*1 	 0.0
1   1 	 0.0*3 + 0.2*7 + 0.0*3 + -0.4*1 	 1.0
1   2 	 0.0*4 + 0.2*5 + 0.0*4 + -0.4*1 	 0.6
2   0 	 0.0*1 + 0.0*2 + 0.3333333333333333*1 + -0.3333333333333333*1 	 0.0
2   1 	 0.0*3 + 0.0*7 + 0.3333333333333333*3 + -0.3333333333333333*1 	 0.6666666666666667
2   2 	 0.0*4 + 0.0*5 + 0.3333333333333333*4 + -0.3333333333333333*1 	 1.0
3   0 	 0.0*1 + 0.0*2 + 0.0*1 + 1.0*1 	 1.0
3   1 	 0.0*3 + 0.0*7 + 0.0*3 + 1.0*1 	 1.0
3   2 	 0.0*4 + 0.0*5 + 0.0*4 + 1.0*1 	 1.0
[[0.         0.         0.         1.        ]
 [0.66666667 1.         0.66666667 1.        ]
 [1.         0.6        1.         1.        ]]


### Rotate [[1 2 1] [3 7 3] [4 5 4]] by 90 degrees around the x dimension.

In [ ]:

# transformation matrix
transform = ??
print(transform.astype(int))

In [ ]:
print(matrix_multiply_slowly(transform, data.T).T)

### Rotate [[1 2 1] [3 7 3] [4 5 4]] by 90 degrees around the y dimension, and center it on zero.

In [ ]:
# transformation matrix, with extra dimension b/c also translating
rotate = ??
translate = ??
print(rotate.astype(int))
print(translate)
# remember what we just learned: order matters! we want to translate the effect of the rotation, so we pass the translation through the rotation
transform = (translate@rotate)
print(transform)

In [ ]:
print(matrix_multiply_slowly(transform, homogenizedData.T).T)