# About Quiz 3 ...

In [2]:
import numpy as np

Let's make our translation matrix

In [19]:
translate = np.array([[1, 0, -10], [0, 1, 25], [0, 0, 1]])
print(translate)

[[  1   0 -10]
 [  0   1  25]
 [  0   0   1]]


Let's make our scale matrix

In [20]:
scale = np.array([[2, 0, 0], [0, .5, 0], [0, 0, 1]])
print(scale)

[[2.  0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  1. ]]


What happens when we multiply them in this order?

In [21]:
translate@scale

array([[  2. ,   0. , -10. ],
       [  0. ,   0.5,  25. ],
       [  0. ,   0. ,   1. ]])

What happens when we multiply them in this order?

In [22]:
scale@translate

array([[  2. ,   0. , -20. ],
       [  0. ,   0.5,  12.5],
       [  0. ,   0. ,   1. ]])

Alright, let's make some data

In [29]:
data = np.array([[10, 4, 1], [20, 2, 1]])
print(data)

[[10  4  1]
 [20  2  1]]


If I translate my data...

In [33]:
(translate@data.T).T

array([[ 0, 29,  1],
       [10, 27,  1]])

If I scale my data...

In [34]:
(scale@data.T).T

array([[20.,  2.,  1.],
       [40.,  1.,  1.]])

If I translate then scale then transform my data...

In [31]:
((translate@scale)@data.T).T

array([[10., 27.,  1.],
       [30., 26.,  1.]])

If I scale then translate then transform my data...

In [32]:
print(data)
((scale@translate)@data.T).T

[[10  4  1]
 [20  2  1]]


array([[ 0. , 14.5,  1. ],
       [20. , 13.5,  1. ]])

So matrix multiplication is **associative** but not **commutative**:
* (A@B)@C = A@(B@C) but
* A@B != B@A

Which order do you think is a better interpretation of the question in the quiz?

Take home message: **know the order in which you want your transformations done**.