# About Quiz 3 ...

In [1]:
import numpy as np

Let's make our translation matrix

In [2]:
translate = np.array([[1, 0, -10], [0, 1, 25], [0, 0, 1]])
print(translate)

[[  1   0 -10]
 [  0   1  25]
 [  0   0   1]]


Let's make our scale matrix

In [3]:
scale = np.array([[2, 0, 0], [0, .5, 0], [0, 0, 1]])
print(scale)

[[2.  0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  1. ]]


What happens when we multiply them in this order?

In [4]:
translate@scale

array([[  2. ,   0. , -10. ],
       [  0. ,   0.5,  25. ],
       [  0. ,   0. ,   1. ]])

What happens when we multiply them in this order?

In [5]:
scale@translate

array([[  2. ,   0. , -20. ],
       [  0. ,   0.5,  12.5],
       [  0. ,   0. ,   1. ]])

Alright, let's make some data

In [6]:
data = np.array([[10, 4, 1], [20, 2, 1]])
print(data)

[[10  4  1]
 [20  2  1]]


If I translate my data...

In [7]:
(translate@data.T).T

array([[ 0, 29,  1],
       [10, 27,  1]])

If I scale my data...

In [8]:
(scale@data.T).T

array([[20.,  2.,  1.],
       [40.,  1.,  1.]])

If I translate then scale then transform my data...

In [9]:
((translate@scale)@data.T).T

array([[10., 27.,  1.],
       [30., 26.,  1.]])

If I scale then translate then transform my data...

In [10]:
print(data)
((scale@translate)@data.T).T

[[10  4  1]
 [20  2  1]]


array([[ 0. , 14.5,  1. ],
       [20. , 13.5,  1. ]])

So matrix multiplication is **associative** but not **commutative**:
* (A@B)@C = A@(B@C) but
* A@B != B@A

Which order do you think is a better interpretation of the question in the quiz?

Take home message: **know the order in which you want your transformations done**.

# About Homework 3

Generally, people seem to know how to set up a transformation matrix:
* translation
* scaling
* rotation in 2D
* rotation in 3D
* max-min normalization

The problem seems to come in actually doing the matrix multiply.

Here's a mnemonic that may help you: Pirates say Argh over the Seas (R over C, rows over columns).

Here's a nice little refresher: https://www.mathsisfun.com/algebra/matrix-multiplying.html.

And here we implement matrix multiply using for loops.

In [11]:
def matrix_multiply_slowly(m1, m2):
    if m1.shape[1] != m2.shape[0]:
        print("Can't multiply a ", m1.shape, " matrix by a ", m2.shape, " matrix.")
        return None
    res = []
    # rows
    for rowIndex in range(m1.shape[0]):
        # over
        res.append([])
        # columns
        for colIndex in range(m2.shape[1]):
            res[-1].append(dot_product_slowly(rowIndex, colIndex, m1[rowIndex], m2[:,colIndex]))
    return np.array(res)

def dot_product_slowly(i, j, v1, v2):
    if len(v1) != len(v2):
        print("Can't multiply a vector of length ", len(v1), " with a vector of length ", len(v2), ".")
        return 0
    pairs = list(zip(v1, v2))
    print(i, ' ', j, '\t', ' + '.join(['%s*%s'%(i, j) for i, j in pairs]), '\t', np.sum([i*j for i, j in pairs]))
    # sum up the pairwise products
    return np.sum([i*j for i, j in pairs])


In [12]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[2,0],[0,3]])
print(m1@m2)

[[ 2  6]
 [ 6 12]]


In [13]:
print(matrix_multiply_slowly(m1, m2))

0   0 	 1*2 + 2*0 	 2
0   1 	 1*0 + 2*3 	 6
1   0 	 3*2 + 4*0 	 6
1   1 	 3*0 + 4*3 	 12
[[ 2  6]
 [ 6 12]]


### Translate [[1 2 1] [3 7 3] [4 5 4]] to the origin along the y and z dimensions.

In [18]:
data = np.array([[1,2,1],[3,7,3],[4,5,4]])

# add trailing 1s for translation
# there is NO NEED to add a bottom row to make the matrix square
homogenizedData = np.append(data, np.array([np.ones(data.shape[0], dtype=int)]).T, axis=1)

# transformation matrix
transform = np.array([[1,0,0,0],[0,1,0,-np.min(data[:, 1])],[0,0,1,-np.min(data[:,2])],[0,0,0,1]])
print(homogenizedData)
print(transform)

[[1 2 1 1]
 [3 7 3 1]
 [4 5 4 1]]
[[ 1  0  0  0]
 [ 0  1  0 -2]
 [ 0  0  1 -1]
 [ 0  0  0  1]]


In [19]:
print(matrix_multiply_slowly(transform, homogenizedData.T).T)

0   0 	 1*1 + 0*2 + 0*1 + 0*1 	 1
0   1 	 1*3 + 0*7 + 0*3 + 0*1 	 3
0   2 	 1*4 + 0*5 + 0*4 + 0*1 	 4
1   0 	 0*1 + 1*2 + 0*1 + -2*1 	 0
1   1 	 0*3 + 1*7 + 0*3 + -2*1 	 5
1   2 	 0*4 + 1*5 + 0*4 + -2*1 	 3
2   0 	 0*1 + 0*2 + 1*1 + -1*1 	 0
2   1 	 0*3 + 0*7 + 1*3 + -1*1 	 2
2   2 	 0*4 + 0*5 + 1*4 + -1*1 	 3
3   0 	 0*1 + 0*2 + 0*1 + 1*1 	 1
3   1 	 0*3 + 0*7 + 0*3 + 1*1 	 1
3   2 	 0*4 + 0*5 + 0*4 + 1*1 	 1
[[1 0 0 1]
 [3 5 2 1]
 [4 3 3 1]]


### Scale [[1 2 1] [3 7 3] [4 5 4]] by 2 along the x dimension and .5 along the y dimension.

In [20]:
# we are only scaling so we don't NEED to add the homogenous coordinate; but if you did I gave you credit
transform = np.array([[2,0,0],[0,.5,0],[0,0,1]])
print(transform)

[[2.  0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  1. ]]


In [21]:
print(matrix_multiply_slowly(transform, data.T).T)

0   0 	 2.0*1 + 0.0*2 + 0.0*1 	 2.0
0   1 	 2.0*3 + 0.0*7 + 0.0*3 	 6.0
0   2 	 2.0*4 + 0.0*5 + 0.0*4 	 8.0
1   0 	 0.0*1 + 0.5*2 + 0.0*1 	 1.0
1   1 	 0.0*3 + 0.5*7 + 0.0*3 	 3.5
1   2 	 0.0*4 + 0.5*5 + 0.0*4 	 2.5
2   0 	 0.0*1 + 0.0*2 + 1.0*1 	 1.0
2   1 	 0.0*3 + 0.0*7 + 1.0*3 	 3.0
2   2 	 0.0*4 + 0.0*5 + 1.0*4 	 4.0
[[2.  1.  1. ]
 [6.  3.5 3. ]
 [8.  2.5 4. ]]


### Perform a local max-min normalization of [[1 2 1] [3 7 3] [4 5 4]].

In [23]:
# transformation matrix
scale = np.array([[1/(np.max(data[:,0])-np.min(data[:, 0])),0,0,0],[0,1/(np.max(data[:,1])-np.min(data[:, 1])),0,0],[0,0,1/(np.max(data[:,2])-np.min(data[:, 2])),0],[0,0,0,1]])
translate = np.array([[1,0,0,-np.min(data[:, 0])],[0,1,0,-np.min(data[:, 1])],[0,0,1,-np.min(data[:,2])],[0,0,0,1]])
print(scale)
print(translate)
# remember what we just learned: order matters! we want to scale the effect of the translation, so we pass the scaling through the translation
# also notice if you do it the other way around we do not get a matrix where every value is between 0 and 1
transform = scale@translate
print(transform)

[[0.33333333 0.         0.         0.        ]
 [0.         0.2        0.         0.        ]
 [0.         0.         0.33333333 0.        ]
 [0.         0.         0.         1.        ]]
[[ 1  0  0 -1]
 [ 0  1  0 -2]
 [ 0  0  1 -1]
 [ 0  0  0  1]]
[[ 0.33333333  0.          0.         -0.33333333]
 [ 0.          0.2         0.         -0.4       ]
 [ 0.          0.          0.33333333 -0.33333333]
 [ 0.          0.          0.          1.        ]]


In [24]:
# max-min means translation AND scaling, so we need that trailing column of ones
print(matrix_multiply_slowly(transform, homogenizedData.T).T)

0   0 	 0.3333333333333333*1 + 0.0*2 + 0.0*1 + -0.3333333333333333*1 	 0.0
0   1 	 0.3333333333333333*3 + 0.0*7 + 0.0*3 + -0.3333333333333333*1 	 0.6666666666666667
0   2 	 0.3333333333333333*4 + 0.0*5 + 0.0*4 + -0.3333333333333333*1 	 1.0
1   0 	 0.0*1 + 0.2*2 + 0.0*1 + -0.4*1 	 0.0
1   1 	 0.0*3 + 0.2*7 + 0.0*3 + -0.4*1 	 1.0
1   2 	 0.0*4 + 0.2*5 + 0.0*4 + -0.4*1 	 0.6
2   0 	 0.0*1 + 0.0*2 + 0.3333333333333333*1 + -0.3333333333333333*1 	 0.0
2   1 	 0.0*3 + 0.0*7 + 0.3333333333333333*3 + -0.3333333333333333*1 	 0.6666666666666667
2   2 	 0.0*4 + 0.0*5 + 0.3333333333333333*4 + -0.3333333333333333*1 	 1.0
3   0 	 0.0*1 + 0.0*2 + 0.0*1 + 1.0*1 	 1.0
3   1 	 0.0*3 + 0.0*7 + 0.0*3 + 1.0*1 	 1.0
3   2 	 0.0*4 + 0.0*5 + 0.0*4 + 1.0*1 	 1.0
[[0.         0.         0.         1.        ]
 [0.66666667 1.         0.66666667 1.        ]
 [1.         0.6        1.         1.        ]]


Bad pipe message: %s [b'\xa6\xfd\xcf\xa0$\xe6?\xd4\x81ve\xd4\x84da[\x0f\xa3 \x0b\xa8\x9f\x90\xf3$\xbd\xca\xc1\x82v\xf3~\x05/\x88\xc0\xf3\x93\xa0@+\x14M\x1f\xc6d_\x1b%Ca\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08\n\x08\x0b\x08\x04\x08\x05\x08\x06\x04\x01']
Bad pipe message: %s [b'\xac\x12h\xa8Y\x99B\xba\xda\xf6 e?\x910x\xc8\xbd Wm\xcd\xaf\xb6\xec\xff\x139\xca\xd9\xf23%\xad\x1e\xcf=L #0S\xbe\xbb\xad\xef<1\x13\xaf\x94\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08\n\x08\x0

### Rotate [[1 2 1] [3 7 3] [4 5 4]] by 90 degrees around the x dimension.

In [ ]:

# transformation matrix
transform = np.array([[1, 0, 0], [0, np.cos(np.radians(90)), -np.sin(np.radians(90))],[0, np.sin(np.radians(90)), np.cos(np.radians(90))]])
print(transform.astype(int))

In [ ]:
print(matrix_multiply_slowly(transform, data.T).T)

### Rotate [[1 2 1] [3 7 3] [4 5 4]] by 90 degrees around the y dimension, and center it on zero.

In [ ]:
# transformation matrix, with extra dimension b/c also translating
# if you like this, look up z-scoring!
rotate = np.array([[np.cos(np.radians(90)), 0, np.sin(np.radians(90)), 0], [0, 1, 0, 0], [-np.sin(np.radians(90)), 0, np.cos(np.radians(90)), 0], [0, 0, 0, 1]])
translate = np.array([[1, 0, 0, -np.mean(data[:, 0])], [0, 1, 0, -np.mean(data[:, 1])], [0, 0, 1, -np.mean(data[:, 2])], [0, 0, 0, 1]])
print(rotate.astype(int))
print(translate)
# remember what we just learned: order matters! we want to translate the effect of the rotation, so we pass the translation through the rotation
transform = (translate@rotate)
print(transform)

In [ ]:
print(matrix_multiply_slowly(transform, homogenizedData.T).T)