Do we remember our data types and summary statistics?
--------------------------

| | Quantitative Continuous | Quantitative Discrete | Qualitative Ordinal | Qualitative Nominal |
|------|------|------|------|------|
| Min |x |x |x | |
| Max |x |x |x | |
| Range|x |x | | |
| SD| x| x| | |
| Mean| x| x| | |
| Median| x| x| | |
| Var| x| x| | |
| Mode| x| x| x| x|



What is a possible mistake we can make with summary statistics on qualitative data?
----------------------------------------------

In [3]:
import pandas as pd

cats = pd.read_csv('data/cats_short.csv')
cats.agg(['min', 'mean', 'median', 'max', 'var'])

C:\Users\Simon\AppData\Local\Temp\ipykernel_9184\2353664718.py:4: FutureWarning: ['Sex', ' "Size"'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  cats.agg(['min', 'mean', 'median', 'max', 'var'])


Unnamed: 0  Sex       Bwt        Hwt     "Size"
min            1.0    F  2.000000   6.300000      large
mean          18.0  NaN  2.222857   8.842857        NaN
median        18.0  NaN  2.200000   8.800000        NaN
max           35.0    F  2.500000  11.200000   smallest
var          105.0  NaN  0.016521   1.558992        NaN

Let's look more at numpy
----------------------------------------

https://numpy.org/

In [7]:
import numpy as np

Data times in numpy:
| Programming name | Math name |
|------|------|
| not even | scalar |
| 1d array | vector |
| 2d array | matrix |
| 3d array | tensor |

In [11]:
v = np.array([1, 2, 3])
m = np.array([[1,2,3], [4,5,6]])
t = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

print(v)
print(m)
print(t)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
# what do these look like?
## let's take a look at ndim, size, shape
# print(t.ndim)
# print(t.size)
# print(t.shape)
# how can we index into these?
# v[1]
# m[1][1]
# t[1][1][1]
# how can we manipulate these? concatenating them, sorting them, broadcasting 
m/2
m.dtype

# how do I reverse sort?
v.sort()
v


array([1, 2, 3])

In [26]:
# let's get some summary statistics

cats = np.genfromtxt('data/cats_short.csv', delimiter=',', names=True, dtype=None, encoding='utf8')
for col in ['Hwt', 'Bwt']:
    print(cats[col].min(), data[col].mean(), data[col].max())
print(cats['Size'].max())

NameError: name 'data' is not defined

Why numpy?
----------

Numpy is space efficient
(reference: https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/)

In [27]:
# importing numpy package
import numpy as np
  
# importing system module
import sys
  
# declaring a list of 1000 elements 
S= range(1000)
  
# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(S))
  
# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
  
# declaring a Numpy array of 1000 elements 
D= np.arange(1000)
  
# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
  
# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  24
Size of the whole list in bytes:  24000
Size of each element of the Numpy array in bytes:  4
Size of the whole Numpy array in bytes:  4000


Numpy *can be* more time efficient (reference: https://stackoverflow.com/questions/9708783/numpy-vs-list-comprehension-which-is-faster)

In [28]:
import sys, numpy
import timeit

def numpysum(n):
    a = numpy.arange(n) ** 2
    b = numpy.arange(n) ** 3
    return a + b

def pythonsum(n):
    a = [i ** 2 for i in range(n)]
    b = [i ** 3 for i in range(n)]
    return [a[i] + b[i] for i in range(n)]

for size in [10, 100, 1000]:
    print(size)
    print(timeit.timeit(lambda: pythonsum(size)))
    print(timeit.timeit(lambda: numpysum(size)))

10
18.879551199999923
11.13523229999987
100
153.42707410000003
14.15387480000004
1000


More on jupyter and data science
----------------------------

https://docs.jupyter.org/en/latest/

https://dl.acm.org/doi/pdf/10.1145/3173574.3173748