Do we remember our data types and summary statistics?
--------------------------

|Aggregate Stat | Quantitative Continuous | Quantitative Discrete | Qualitative Ordinal | Qualitative Nominal |
|------|------|------|------|------|
| Min | yes | yes | yes | no |
| Max | yes | yes | yes | no |
| mean | yes | yes | no | no |
| median | yes| yes| yes| no |
| mode | yes | yes | yes | yes |
| unique values | yes | yes | yes | yes |
| sort | yes | yes | yes | no |
| range | yes | yes | yes | no |
| variance | yes | yes | no | no |


What is a possible mistake we can make with summary statistics on qualitative data?
----------------------------------------------

In [12]:
import pandas as pd

cats = pd.read_csv('data/cats_short.csv')
cats.agg(['min', 'mean', 'median', 'max', 'var'])

/var/folders/yy/b58prrrs6klfnptx1dcbmbmh0000gn/T/ipykernel_4560/2353664718.py:4: FutureWarning: ['Sex', ' "Size"'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  cats.agg(['min', 'mean', 'median', 'max', 'var'])


Unnamed: 0  Sex       Bwt        Hwt     "Size"
min            1.0    F  2.000000   6.300000      large
mean          18.0  NaN  2.222857   8.842857        NaN
median        18.0  NaN  2.200000   8.800000        NaN
max           35.0    F  2.500000  11.200000   smallest
var          105.0  NaN  0.016521   1.558992        NaN

panda sorts by size


Let's look more at numpy
----------------------------------------

https://numpy.org/


https://numpy.org/doc/stable/ <-- look here!!

- the computer rep of linear alg


In [6]:
import numpy as np

Data times in numpy:
| Programming name | Math name |
|------|------|
| 1d array | vector |
| 2d array | matrix |
| 3d array | tensor |

gpus are set up to operate on vectors and matrices  

tpu tensor processing unit
- 3d arrays / tensors



In [14]:
v = np.array([1, 2, 3])
m = np.array([[1,2,3], [4,5,6]])
t = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print (v)
print(m)
print(t)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# what do these look like?
## let's take a look at ndim, size, shape
#print(v.ndim)
#print(v.size) #has three lements
# print(v.shape) #3 in first dimension, and nothing else
# print(m.ndim)
# print(m.size)
# print(m.shape) #2 dimensions, 3 in each dimension
# print(t.ndim)
# print(t.size)
# print(t.shape) #2 in each dimension
# how can we index into these?
#what if i want the second item in v
# print(v[1])
# print(m[1][1])
# print(m[1]) 
# how can we manipulate these? concatenating them, sorting them, broadcasting 
# print(m)
# m*2 #every element * 2
# m/2
# (m/2).dtype #int to float

#sorting v
v.sort()
v
#how do I reverse sort???

array([1, 2, 3])

slice of a matrix is a vector
slice of a tensor is a matrix or another tensor

In [34]:
# let's get some summary statistics

cats = np.genfromtxt('data/cats_short.csv', delimiter=',', names=True, dtype=[int, str, float, float, str], encoding='utf8')
for col in ['Hwt', 'Bwt']: #^^dtypes are wrong that's why it won't work
    print(cats[col].min(), data[col].mean(), data[col].max())
print(cats['Size'].max())

NameError: name 'data' is not defined

Why numpy?
----------

Numpy is space efficient
(reference: https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/)

- very space efficient because it's based on C

In [35]:
# importing numpy package
import numpy as np
  
# importing system module
import sys
  
# declaring a list of 1000 elements 
S= range(1000)
  
# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(S))
  
# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
  
# declaring a Numpy array of 1000 elements 
D= np.arange(1000)
  
# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
  
# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


Numpy *can be* more time efficient (reference: https://stackoverflow.com/questions/9708783/numpy-vs-list-comprehension-which-is-faster)

In [36]:
import sys, numpy
import timeit #times things, use numpy for fast programming

def numpysum(n):
    a = numpy.arange(n) ** 2
    b = numpy.arange(n) ** 3
    return a + b

def pythonsum(n):
    a = [i ** 2 for i in range(n)]
    b = [i ** 3 for i in range(n)]
    return [a[i] + b[i] for i in range(n)]

for size in [10, 100, 1000]:
    print(size)
    print(timeit.timeit(lambda: pythonsum(size)))
    print(timeit.timeit(lambda: numpysum(size)))

10
9.314269728999989
3.482872420000149
100
82.18041706299982
3.8740782579998267
1000


More on jupyter and data science
----------------------------

https://docs.jupyter.org/en/latest/

https://dl.acm.org/doi/pdf/10.1145/3173574.3173748
- paper about how data scienctists use Jupyter

- 