Let's talk more! about matrices
----------------------

* What is the identity matrix?
* What is the transpose of a matrix?
* What is a diagonal matrix?

In [1]:
import numpy as np

# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
# transposing a matrix
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
np.matrix.transpose(np.ones([3, 2]))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.ones([3, 2]).T

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# flattening a matrix
# way one
print(np.ndarray.flatten(np.ones([3, 2])))
# way two
print(np.reshape(np.ones([3, 2]), -1))

[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]


In [6]:
# what is a diagonal matrix?


Let's review our matrix math
----------------------------

* What is a scalar?
* What is a vector?
* What is a matrix?
* What is a tensor?

* How can I multiply a vector times a scalar?
* What is the dot product between two vectors?
* How can I multiply a matrix times a vector?
* How can I multiply a matrix times a matrix?
* What has to be true in order for me to be able to calculate the dot product between two vectors?
* What has to be true in order for me to be able to multiply a matrix times a vector, or multiply two matrices?



Let's start with scalars. How do we:
* add/subtract
* multiply/divide
two scalars?

In [9]:
x = 2
y = 4.5

# add

# subtract

# multiply

# divide


Now let's talk about vectors. How do we:
* add/subtract a scalar to/from a vector?
* multiply/divide a vector by a scalar?

Also, how do we:
* add/subtract
* multiply/divide
two vectors?

In [10]:
xv = np.array([1, 6, 2])

print("math on a vector and a scalar")

# add x to xv
print(x + xv)

# subtract x from xv
print(xv - x)

# multiply xv times x
print(xv * x)

# divide xv by x
print(xv / x)

math on a vector and a scalar
[3 8 4]
[-1  4  0]
[ 2 12  4]
[0.5 3.  1. ]


In [11]:
yv = np.array([2.2, 5.4, 1.1])

print("math on two vectors")

# add xv and yv
print(xv + yv)

# subtract yv from xv
print(xv - yv)

# multiply xv and yv
# what exactly is this doing?
print(np.dot(xv, yv))

# what exactly is this doing?
print(np.outer(xv, yv))

# what exactly is this doing?
print(xv * yv)

# divide xv by yv
print(np.divide(xv, yv))
print(xv / yv)
print(xv // yv)

math on two vectors
[ 3.2 11.4  3.1]
[-1.2  0.6  0.9]
36.800000000000004
[[ 2.2  5.4  1.1]
 [13.2 32.4  6.6]
 [ 4.4 10.8  2.2]]
[ 2.2 32.4  2.2]
[0.45454545 1.11111111 1.81818182]
[0.45454545 1.11111111 1.81818182]
[0. 1. 1.]


What are some "gotchas" with vector math?

Great! Now let's talk about matrices. How do we:
* add/subtract a scalar to/from a matrix?
* multiply/divide a matrix by a scalar?

Also, how do we:
* add/subtract a vector from a matrix?
* multiply/divide a matrix by a vector?

And finally, how do we:
* add/subtract
* multiply/divide
two matrices?

In [16]:
xm = np.array([[3,5,3], [4,2,4]])

# add / subtract a scalar

# multiply / divide by a scalar

# add / subtract a vector


array([[ 2, -1,  1],
       [ 3, -4,  2]])

In [ ]:
# multiply / divide by a vector

# what are we doing in each row here?
print(np.matmul(xm, xv))
print(np.multiply(xm, xv))

In [14]:
# and which of those do we think this corresponds to?
print(xm * xv)

[[ 3 30  6]
 [ 4 12  8]]


What are some "gotchas" with matrix/matrix math?
* multiplication not commutative

**What does all this have to do with data analytics, visualization and machine learning?**

We might want to:
* translate (move)
* scale (resize)
* rotate
* normalize
* orthographic projection
data sets to get insight!

Resources
---------

* http://cs229.stanford.edu/summer2019/cs229-linalg.pdf and https://klaviyo.github.io/datascience-learning/linear-algebra/cs229.html
* https://bvanderlei.github.io/jupyter-guide-to-linear-algebra/intro.html


In [ ]:
# Challenge!!

# ok, take these two arrays and add a column to the first one that consists of the second one, go on, I dare you!

arrayFirst = np.reshape(np.arange(0, 10), [5, 2])
print(arrayFirst)

arraySecond = np.array([[2], [3]])
print(arraySecond)

arrayFirst[: 1] = arraySecond

In [ ]:
# hmm, let's use reshape
arrayFirst[: 1] = np.reshape(arraySecond, [1, 2])
print(arrayFirst)