# Review; Q&A

## That ix_ thing

In [13]:
import numpy as np

data = np.array([[0, 1, 2, 3, 4], [10, 11, 12, 13, 14], [20, 21, 22, 23, 24]])
print(data)
# Notice it always *ends with the row size*; so you figure out the length of shape tells you the number of dimensions (ndim!), then the last element in shape is rows and the second last is columns
print(data.shape)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]
(3, 5)


What if I want the columns indexed at 1 and 4, for the rows indexed at 0 and 2?

In [3]:
print(data[np.ix_([0, 2], [1, 4])])


[[ 1  4]
 [21 24]]


## Summing Across Whole Matrices in 3 Dim Numpy Array

In [4]:
nptensorFloat = np.ones([3, 4, 5])
print(nptensorFloat)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [10]:
# dimension 0: forward through each matrix 
np.sum(nptensorFloat, axis=0)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [8]:
# dimension 1: down through each column
np.sum(nptensorFloat, axis=1)


array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [9]:
# dimension 2: across through each row
np.sum(nptensorFloat, axis=2)


array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [12]:
# sum of the sum across the rows
np.sum(np.sum(nptensorFloat, axis=2), axis=1)

array([20., 20., 20.])

# Let's talk about matrices

* What is a matrix?
* What is the identity matrix?
* What is the transpose of a matrix?
* What is a diagonal matrix?

## Identity matrix, in numpy

In [2]:
import numpy as np

# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Transposing a matrix, in numpy

A *transpose* of an array is a new array in which the rows of the old array (in order) become the columns of the new array (in order).

In [11]:
# give me a matrix
nparray = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
print(nparray)
print(nparray.shape)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]


In [13]:
# one way to transpose it
transpose = np.matrix.transpose(nparray)
print(transpose)
print(transpose.shape)

[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]]
(4, 3)


In [14]:
# another way to transpose it
transpose = nparray.T
print(transpose)
print(transpose.shape)

[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]]
(4, 3)


## Flattening a matrix

In [14]:
# way one
print(np.ndarray.flatten(nparray))

[ 0  1  2  3 10 11 12 13 20 21 22 23 30 31 32 33]


In [16]:
# way two
print(np.reshape(nparray, -1))

[ 0  1  2  3 10 11 12 13 20 21 22 23 30 31 32 33]


## What is a diagonal matrix?

# Basic matrix math

We will cover:

* How can I multiply a vector or matrix times a scalar?
* What is the *dot product* between two vectors?
* How can I multiply a matrix times a vector?
* How can I multiply a matrix times a matrix?
* What has to be true in order for me to be able to calculate the dot product between two vectors?
* What has to be true in order for me to be able to multiply a matrix times a vector, or multiply two matrices?

## Scalars


Let's start with scalars. How do we:
* add/subtract
* multiply/divide
two scalars?

In [4]:
x = 2
y = 4.5

# add

# subtract

# multiply

# divide


## Vectors


### Vectors and Scalars

How do we:
* add/subtract a scalar to/from a vector?
* multiply/divide a vector by a scalar?

In [5]:
xv = np.array([1, 6, 2])
print("xv", xv)
print("x", x)

print("math on a vector and a scalar")

# add x to xv
print("xv plus x", xv + x)

# subtract x from xv
print("xv minus x", xv - x)



xv [1 6 2]
x 2
math on a vector and a scalar
xv plus x [3 8 4]
xv minus x [-1  4  0]


How do we:
* multiply/divide a vector by a scalar?

In [ ]:
# multiply xv times x
print("xv times x", xv * x)

# divide xv by x
# note how the type changes
print("xv divied by x", xv / x)

### Vectors and vectors

How do we add/subtract two vectors?

When we add/subtract two vectors we do it "element wise". This means the two vectors *have to be of equal length*. (And that is why I'm always printing out the shapes of numpy arrays!)

In [8]:
yv = np.array([2.2, 5.4, 1.1])
print("xv", xv)
print("yv", yv)

print("math on two vectors")

# add xv and yv
# note how the result is float, even though xv was int
print("xv + yv", xv + yv)

# subtract yv from xv
print("xv minus yv", xv - yv)

xv [1 6 2]
yv [2.2 5.4 1.1]
math on two vectors
xv + yv [ 3.2 11.4  3.1]
xv minus yv [-1.2  0.6  0.9]


How do wemultiply/divide two vectors?

There are **two ways**!

Forst let's look at the "element wise product" of two vectors. That's what you get if you use * or /.

In [21]:
# multiply xv and yv
print("xv times yv", xv * yv)

# divide xv by yv
print("xv / yv", xv / yv)

xv times yv [ 2.2 32.4  2.2]
xv / yv [0.45454545 1.11111111 1.81818182]


Now let's look at the *dot product* between two vectors (also called the "scalar product" or inner product) is calculated by:
1. multiplying the two vectors element-wise
2. summing the products to get a single scalar

It looks like this: $d(\vec{a}, \vec{b}) = \sum_{i=0}^{N-1} a_i*b_i$

Let's work one out by hand:
* $xv = \begin{pmatrix} 1 & 6 & 2 \end{pmatrix}$
* $yv = \begin{pmatrix} 2.2 & 5.4 & 1.1 \end{pmatrix}$
* $xv \cdot yv = $

In [26]:
# dot product of xv and yv
print("xv dot yv", xv.dot(yv))

xv dot yv 36.800000000000004


Another way to write it in numpy is "@"

In [30]:
print("xv dot yv", xv@yv)

xv dot yv 36.800000000000004


## Matrices

### Matrices and scalars

Great! How do we:
* add/subtract a scalar to/from a matrix?
* multiply/divide a matrix by a scalar?

In [16]:
xm = np.array([[3,5,3], [4,2,4]])
print("xm", xm)
print("x", x)

# add xm and x
print("xm plus x", )

# subtract x from xm
print("xm minus x", )

# multiply xm by x
print("xm times x", )

# divide xm by x
print("xm divided by x", )


xm [[3 5 3]
 [4 2 4]]
x 2
xm plus x
xm minus x
xm times x
xm divided by x


### Matrices and vectors

How do we add/subtract a vector from a matrix?

You can see that this also happens element-wise.

In [36]:
print("xm", xm)
print("xv", xv)

# add xm and xv
print("xm plus xv", )


# subtract xv from xm
print("xm minus xv", )



xm [[3 5 3]
 [4 2 4]]
xv [1 6 2]
xm plus xv
xm minus xv


How do we multiply a matrix by a vector?

Matrix-vector multiplication is built on the *dot product* between two vectors.

Note: the length of each row in the matrix has to be the same as the length of the vector. If it's not, you won't be able to multiply.

Let's work this out by hand:
* $XM = \begin{pmatrix} 3 & 5 & 3 \\ 4 & 2 & 4 \end{pmatrix}$
* $xv = \begin{pmatrix} 1 & 6 & 2 \end{pmatrix}$
* $XM \cdot xv = $

In [34]:
print(xm.shape)
print(xv.shape)

# dot product
print("xm dot xv", xm@xv)

(2, 3)
(3,)
xm dot xv [39 24]


(If you want the element wise product of a matrix and a vector, use *multiply*.)

In [27]:
# if you want element wise product
print("xm multiply xv", np.multiply(xm, xv))

xm multiply xv [[ 3 30  6]
 [ 4 12  8]]


Stay away from "*" and "/" when it comes to matrices, it'll just confuse things. Use "@" for the dot product.

### Matrices and matrices

And finally, how do we multiply two matrices?

Matrix multiplication is the dot product of each row in the first matrix and each column in the second matrix.

This means that the length of each row in the first matrix has to be the same as that of each column in the second matrix.

If it's not, we can't multiply.

In [36]:
print(xm.shape)

# attempt matrix multiply
xm@xm

(2, 3)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

But we *can* multiply $xm$ and $xm^T$ (the transpose of $xm$)!

In [38]:
print(xm)
print(xm.shape)
print(xm.T.shape)

# attempt matrix multiply
xm@xm.T

[[3 5 3]
 [4 2 4]]
(2, 3)
(3, 2)


array([[43, 34],
       [34, 36]])

Let's work this out by hand:
* $XM = \begin{pmatrix} 3 & 5 & 3 \\ 4 & 2 & 4 \end{pmatrix}$
* $XM^T = \begin{pmatrix} 3 & 4 \\ 5 & 2 \\ 3 & 4 \end{pmatrix}$
* $XM \cdot XM^T = $


What are some "gotchas" with matrix/matrix math?
* multiplication *is* associative
multiplication *is not* commutative

# What does all this have to do with data analytics, visualization and machine learning?

We might want to:
* translate (move)
* scale (resize)
* rotate
* normalize
* orthographically project
data sets to get insight!

We do all of those via matrix math.

(*And what hardware is really good at matrix math?*)

# Resources

* http://cs229.stanford.edu/summer2019/cs229-linalg.pdf and https://klaviyo.github.io/datascience-learning/linear-algebra/cs229.html
* https://bvanderlei.github.io/jupyter-guide-to-linear-algebra/intro.html


# Challenge!!

In [52]:
# ok, take these two arrays and add a column to the first one that consists of the second one, go on, I dare you!

arrayFirst = np.reshape(np.arange(0, 10), [5, 2])
print(arrayFirst)

arraySecond = np.array([[2], [3]])
print(arraySecond)

arrayFirst[: 1] = arraySecond

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[2]
 [3]]


ValueError: could not broadcast input array from shape (2,1) into shape (1,2)

In [53]:
# hmm, let's use reshape
arrayFirst[: 1] = np.reshape(arraySecond, [1, 2])
print(arrayFirst)

[[2 3]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
