# Let's talk about matrices

* What is a matrix?
* What is the identity matrix?
* What is the transpose of a matrix?
* What is a diagonal matrix?

## Identity matrix, in numpy

In [6]:
import numpy as np

# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Transposing a matrix, in numpy

In [10]:
# give me a matrix
nparray = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23], [30, 31, 32, 33]])
print(nparray)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


In [12]:
# one way to transpose it
transpose = np.matrix.transpose(nparray)
print(transpose)

[[ 0 10 20 30]
 [ 1 11 21 31]
 [ 2 12 22 32]
 [ 3 13 23 33]]


In [13]:
# another way to transpose it
transpose = nparray.T
print(transpose)

[[ 0 10 20 30]
 [ 1 11 21 31]
 [ 2 12 22 32]
 [ 3 13 23 33]]


## Flattening a matrix

In [14]:
# way one
print(np.ndarray.flatten(nparray))

[ 0  1  2  3 10 11 12 13 20 21 22 23 30 31 32 33]


In [16]:
# way two
print(np.reshape(nparray, -1))

[ 0  1  2  3 10 11 12 13 20 21 22 23 30 31 32 33]


## What is a diagonal matrix?

# Basic matrix math

Review:

* What is a scalar?
* What is a vector?
* What is a matrix?
* What is a tensor?

Now we will cover:

* How can I multiply a vector or matrix times a scalar?
* What is the *dot product* between two vectors?
* How can I multiply a matrix times a vector?
* How can I multiply a matrix times a matrix?
* What has to be true in order for me to be able to calculate the dot product between two vectors?
* What has to be true in order for me to be able to multiply a matrix times a vector, or multiply two matrices?

## Scalars


Let's start with scalars. How do we:
* add/subtract
* multiply/divide
two scalars?

In [18]:
x = 2
y = 4.5

# add

# subtract

# multiply

# divide


## Vectors


### Vectors and Scalars

How do we:
* add/subtract a scalar to/from a vector?
* multiply/divide a vector by a scalar?

In [24]:
xv = np.array([1, 6, 2])
print("xv", xv)
print("x", x)

print("math on a vector and a scalar")

# add x to xv
print("xv plus x", xv + x)

# subtract x from xv
print("xv minus x", xv - x)



xv [1 6 2]
x 2
math on a vector and a scalar
xv plus x [3 8 4]
xv minus x [-1  4  0]
xv times x [ 2 12  4]
xv divied by x [0.5 3.  1. ]


How do we:
* multiply/divide a vector by a scalar?

In [ ]:
# multiply xv times x
print("xv times x", xv * x)

# divide xv by x
# note how the type changes
print("xv divied by x", xv / x)

### Vectors and vectors

How do we:
* add/subtract two vectors?

In [27]:
yv = np.array([2.2, 5.4, 1.1])
print("xv", xv)
print("yv", yv)

print("math on two vectors")

# add xv and yv
# note how the result is float, even though xv was int
print("xv + yv", xv + yv)

# subtract yv from xv
print("xv minus yv", xv - yv)

xv [1 6 2]
yv [2.2 5.4 1.1]
math on two vectors
xv + yv [ 3.2 11.4  3.1]
xv minus yv [-1.2  0.6  0.9]
dot product of xv and yv 36.800000000000004
outer product of xv and vy [[ 2.2  5.4  1.1]
 [13.2 32.4  6.6]
 [ 4.4 10.8  2.2]]
xv times yv [ 2.2 32.4  2.2]
xv divided by yv [0.45454545 1.11111111 1.81818182]
xv / yv [0.45454545 1.11111111 1.81818182]
xv // yv [0. 1. 1.]


How do we:
* multiply/divide two vectors?

In [ ]:
# multiply xv and yv
# what exactly is this doing?
print("dot product of xv and yv", np.dot(xv, yv))

# what exactly is this doing?
print("outer product of xv and vy", np.outer(xv, yv))

# what exactly is this doing?
print("xv times yv", xv * yv)

# divide xv by yv
print("xv divided by yv", np.divide(xv, yv))
print("xv / yv", xv / yv)

# what exactly is this doing?
print("xv // yv", xv // yv)

## Matrices

### Matrices and scalars

Great! How do we:
* add/subtract a scalar to/from a matrix?
* multiply/divide a matrix by a scalar?

In [29]:
xm = np.array([[3,5,3], [4,2,4]])
print("xm", xm)
print("x", x)

# add xm and x
print("xm plus x", )

# subtract x from xm
print("xm minus x", )

# multiply xm by x
print("xm times x", )

# divide xm by x
print("xm divided by x", )


xm [[3 5 3]
 [4 2 4]]
x 2


### Matrices and vectors

How do we:
* add/subtract a vector from a matrix?

In [36]:
print("xm", xm)
print("xv", xv)

# add xm and xv
print("xm plus xv", )


# subtract xv from xm
print("xm minus xv", )



xm [[3 5 3]
 [4 2 4]]
xv [1 6 2]
xm plus xv
xm minus xv


How do we:
* multiply a matrix by a vector?

In [54]:
# what are we doing in each row here?
print("xm matmul xv", np.matmul(xm, xv))

# what are we doing in each row here?
print("xm dot xv", xm.dot(xv))

# what are we doing in each row here?
print("xm multiply xv", np.multiply(xm, xv))

xm matmul xv [39 24]
xm multiply xv [[ 3 30  6]
 [ 4 12  8]]
xm dot xv [39 24]


In [55]:
# and which of those do we think this corresponds to?
print("xm times xv", xm * xv)

xm times xv [[ 3 30  6]
 [ 4 12  8]]


In [56]:
# and which of these do we think this corresponds to?
print("xm @ xv", xm@xv)

xm @ xv [39 24]


(As a reminder, dividing is the same thing as multiplying by the inverse)

In [49]:
# divide xm by xv
xvinv = 1 / xv
print("xv", xv)
print("xvinv", xvinv)
print("xm", xm)

print("xm times xvinv", xm * xvinv)

print("xm @ xvinv", xm@xvinv)


xv [1 6 2]
xvinv [1.         0.16666667 0.5       ]
xm [[3 5 3]
 [4 2 4]]
xm times xvinv [[3.         0.83333333 1.5       ]
 [4.         0.33333333 2.        ]]
xm @ xvinv [5.33333333 6.33333333]


### Matrices and matrices

And finally, how do we:
* multiply
two matrices?

Matrix multiplication is special because...?

In [57]:
# what does this do?
xm*xm

array([[ 9, 25,  9],
       [16,  4, 16]])

In [58]:
# and what does this do?
xm@xm.T

array([[43, 34],
       [34, 36]])

What are some "gotchas" with matrix/matrix math?
* multiplication not commutative

# What does all this have to do with data analytics, visualization and machine learning?

We might want to:
* translate (move)
* scale (resize)
* rotate
* normalize
* orthographically project
data sets to get insight!

We do all of those via matrix math.

(*And what hardware is really good at matrix math?*)

# Resources

* http://cs229.stanford.edu/summer2019/cs229-linalg.pdf and https://klaviyo.github.io/datascience-learning/linear-algebra/cs229.html
* https://bvanderlei.github.io/jupyter-guide-to-linear-algebra/intro.html


# Challenge!!

In [52]:
# ok, take these two arrays and add a column to the first one that consists of the second one, go on, I dare you!

arrayFirst = np.reshape(np.arange(0, 10), [5, 2])
print(arrayFirst)

arraySecond = np.array([[2], [3]])
print(arraySecond)

arrayFirst[: 1] = arraySecond

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[2]
 [3]]


ValueError: could not broadcast input array from shape (2,1) into shape (1,2)

In [53]:
# hmm, let's use reshape
arrayFirst[: 1] = np.reshape(arraySecond, [1, 2])
print(arrayFirst)

[[2 3]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
