In [7]:
import numpy as np

m1 = np.array([[2,3,4], [5,6,7], [8,9,1], [2, 3, 5]])
m2 = np.array([[2,2,2,2], [2,2,2,2], [2,2,2,2]])

print(m1)
print(m2)
print(m1.shape)
print(m2.shape)
print(m2@m1)
print((m2@m1).shape)

[[2 3 4]
 [5 6 7]
 [8 9 1]
 [2 3 5]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
(4, 3)
(3, 4)
[[34 42 34]
 [34 42 34]
 [34 42 34]]
(3, 3)


How does matrix multiplication work? You multiply and sum across rows of m1 and columns of m2.
    
    
So m1@m2 is:

In [15]:
def matrixMultiply(m1, m2):
    m3 = np.zeros([m1.shape[0], m2.shape[1]], dtype=int)
    for i in range(m1.shape[0]):
        for j in range(m2.shape[1]):
            for k in range(m1.shape[1]):
                print(i, j, k, m1[i, k], m2[k, j], m3[i, j], m1[i,k] * m2[k, j])
                m3[i, j] += m1[i, k] * m2[k, j]
    return m3
            
m3 = matrixMultiply(m2, m1)
print(m3)

0 0 0 2 2 0 4
0 0 1 2 5 4 10
0 0 2 2 8 14 16
0 0 3 2 2 30 4
0 1 0 2 3 0 6
0 1 1 2 6 6 12
0 1 2 2 9 18 18
0 1 3 2 3 36 6
0 2 0 2 4 0 8
0 2 1 2 7 8 14
0 2 2 2 1 22 2
0 2 3 2 5 24 10
1 0 0 2 2 0 4
1 0 1 2 5 4 10
1 0 2 2 8 14 16
1 0 3 2 2 30 4
1 1 0 2 3 0 6
1 1 1 2 6 6 12
1 1 2 2 9 18 18
1 1 3 2 3 36 6
1 2 0 2 4 0 8
1 2 1 2 7 8 14
1 2 2 2 1 22 2
1 2 3 2 5 24 10
2 0 0 2 2 0 4
2 0 1 2 5 4 10
2 0 2 2 8 14 16
2 0 3 2 2 30 4
2 1 0 2 3 0 6
2 1 1 2 6 6 12
2 1 2 2 9 18 18
2 1 3 2 3 36 6
2 2 0 2 4 0 8
2 2 1 2 7 8 14
2 2 2 2 1 22 2
2 2 3 2 5 24 10
[[34 42 34]
 [34 42 34]
 [34 42 34]]


Now let's consider the special case of multiplying by the identity matrix. The only element from m1 that will be included in m3 (the output) is the ith element of the ith row. So it really just gives us back the input (hence, "identity" matrix!).

In [49]:
# note homogenous coordinate
m1 = np.array([[2,3,4,1], [5,6,7,1], [8,9,1,1], [2, 3, 5,1]])
# note identity matrix
m2 = np.array([[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]])
print(matrixMultiply(m2, m1.T).T)

[[2 3 4 1]
 [5 6 7 1]
 [8 9 1 1]
 [2 3 5 1]]


Now let's consider translation. The transformation matrix is the identity matrix with the last column modified to do the translation (the addition / subtraction). So:
* the only elements from m1 that will be included in m3 (the output) is the ith element of the ith row and the *last element* of that row
* because we use homogenous coordinate, the *last element* of that row is always 1

In [47]:
# note homogenous coordinate
m1 = np.array([[2,3,4,1], [5,6,7,1], [8,9,1,1], [2, 3, 5,1]])
# note -4350 in last column for translating the prices down by 4350
m2 = np.array([[1,0,0,-4350], [0,1,0,0], [0,0,1,0], [0,0,0,1]])
print(matrixMultiply(m2, m1.T).T)

[[-4348     3     4     1]
 [-4345     6     7     1]
 [-4342     9     1     1]
 [-4348     3     5     1]]


... And *that* (homogenous coordinate + identity matrix) is how we get addition/subtraction out of matrix multiplication!

Adding this cell to try submodules

In [5]:
import numpy as np
tm = np.array([[1, 0, -1], [0, 1, 0], [0, 0, 1]])
dm = np.array([[1, 2, 1], [3, 4, 1]])
(tm @ dm.T).T

array([[0, 2, 1],
       [2, 4, 1]])

In [16]:
matrixMultiply(tm, dm.T)

0 0 0 1 1 0 1
0 0 1 0 2 1 0
0 0 2 -1 1 1 -1
0 1 0 1 3 0 3
0 1 1 0 4 3 0
0 1 2 -1 1 3 -1
1 0 0 0 1 0 0
1 0 1 1 2 0 2
1 0 2 0 1 2 0
1 1 0 0 3 0 0
1 1 1 1 4 0 4
1 1 2 0 1 4 0
2 0 0 0 1 0 0
2 0 1 0 2 0 0
2 0 2 1 1 0 1
2 1 0 0 3 0 0
2 1 1 0 4 0 0
2 1 2 1 1 0 1


array([[0, 2],
       [2, 4],
       [1, 1]])