Let's talk more! about numpy
----------------------

**Going from lists to arrays and figuring out if that worked well...**

In [2]:
import numpy as np
import pickle as pkl #data storage for python to look at 

# how do I make a numpy array from a python list?
pylist = [[10, 1, 2021], [2, 9, 2022]] #python list --> doesn't have a shape but would be 2, 3
nparray = np.array(pylist)

# how do I print a numpy array?
print(nparray)
print(nparray.shape)

#^for converting between numpy array and numpy list

with open('data.pkl','wb') as f:
    pkl.dump(nparray, f)

# and back to a list?

with open('data.pkl','wb') as f:
    nparray2 = pkl.load(f)
    print(nparray2)

backtolist = nparray.tolist()
print(backtolist)

#pickle as pkl 
#can save, dump, load kinds of python objects with numpy and python arrays and lists

#can have numpy lists of 1,2,3,4 dimensions, etc
#for nparray, each array in it should be the same length


[[  10    1 2021]
 [   2    9 2022]]
(2, 3)


UnsupportedOperation: read

In [3]:
# how do I figure out the type of a numpy array? 
print(nparray.dtype)

# hmm, will this work and why or why not?
print(backtolist.dtype)#can't do this because dtpye only works for numpy array

#int64 output means they're ints --> quantitative discrete (floats are continuous)

int32


NameError: name 'backtolist' is not defined

In [4]:
# how do I change the type of a numpy array?
nparrayFloat = nparray.astype(float) #can coerce numpy array into floats (coercing int to float makes it bigger, takes space)
print(nparrayFloat.dtype)
print(nparrayFloat)
#.astype

nparrayStr = np.array(nparrayFloat, dtype=str)
print(nparrayStr.dtype)
#make new array, then tell them to be strings
#coerce into strings for new numpy array
print(nparrayStr)

nparrayFloat = nparrayStr.astype(float)
print(nparrayFloat.dtype)
#try to coerce strings into floats
print(nparrayFloat)

#going from float to int will truncate, so be careful with this

float64
[[1.000e+01 1.000e+00 2.021e+03]
 [2.000e+00 9.000e+00 2.022e+03]]
<U32
[['10.0' '1.0' '2021.0']
 ['2.0' '9.0' '2022.0']]
float64
[[1.000e+01 1.000e+00 2.021e+03]
 [2.000e+00 9.000e+00 2.022e+03]]


In [5]:
# (review!) how do I see the number of dimensions, number of elements, and shape of a numpy array?
print(nparray.size)
#can only have an odd number of elements with an odd number of rows or when it's 1 dimensional
print(nparray.ndim)
print(nparray.shape)

6
2
(2, 3)


**Making numpy arrays...**

In [6]:
# make an array of zeros
nparrayZero = np.zeros([3, 10]) #3 by 10 nparray of zeros
print(nparrayZero)

# that's floats ... what if we want ints?
nparrayZero.astype(int) 
print(nparrayZero) #didn't work

nparrayZero = nparrayZero.astype(int) 
print(nparrayZero) #works

nparrayZeroInt = np.array(nparrayZero, dtype=int)
print(nparrayZeroInt)

# what if we want zeros instead of ones?

nparrayOnes = np.ones([3,10])
print(nparrayOnes)

# what if we want sevens?
nparraySevens = np.ones([3,10])*7 # can broadcast the 7 across all elements like this
print(nparraySevens)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]]


In [7]:
# make an array of random values
nparrayRandomFloat = np.random.random([3, 10])
print(nparrayRandomFloat)
print(nparrayRandomFloat.dtype)

# what if we want random ints? let's see...
#nparrayRandomInt = np.random.random([3, 10], dtype=int) # can't do this because it generates random numbers between 0 and 1


# hmm, if not that then what?
print(((nparrayRandomFloat)*10).astype(int))

#hw^^ what is the other way to do this??


[[0.28119502 0.95357343 0.88104884 0.10963489 0.34584754 0.50390067
  0.03466848 0.53073476 0.04075599 0.08252508]
 [0.28130629 0.06023778 0.30914082 0.06233341 0.58865027 0.04838291
  0.51969353 0.86285701 0.93967261 0.06079304]
 [0.72706173 0.36736293 0.32902674 0.9485838  0.46442562 0.0797577
  0.65550606 0.35993961 0.96892859 0.38950654]]
float64
[[2 9 8 1 3 5 0 5 0 0]
 [2 0 3 0 5 0 5 8 9 0]
 [7 3 3 9 4 0 6 3 9 3]]


In [8]:
# what if we want random floats in an interval?
print(np.linspace(0, 10, 10)) #start, stop, amount
#help(np.linspace)

# what if we want to shape that into a 2 by 5 array?
nplinArray = np.linspace(0,10,10) 
np2dArray = np.reshape(nplinArray, (2, 5))
print(np2dArray)

# what if we want random ints in an interval?
nplinArray = np.linspace(0,10,10, dtype=int)
print(nplinArray) #ints but not random



[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[[ 0.          1.11111111  2.22222222  3.33333333  4.44444444]
 [ 5.55555556  6.66666667  7.77777778  8.88888889 10.        ]]
[ 0  1  2  3  4  5  6  7  8 10]


**Getting access to elements and "slices" of numpy arrays...**

In [9]:
print(nparrayRandomFloat)
print(nparrayRandomFloat.shape)

# (review!) how do I access an element in an array?
print(nparrayRandomFloat[0][0])

# is there a prettier way?
print(nparrayRandomFloat[0, 0])

# this is only marginally prettier for a 2-d array but imagine a 10-d array!

#slice is a chunk basically --> any subarray of the array

[[0.28119502 0.95357343 0.88104884 0.10963489 0.34584754 0.50390067
  0.03466848 0.53073476 0.04075599 0.08252508]
 [0.28130629 0.06023778 0.30914082 0.06233341 0.58865027 0.04838291
  0.51969353 0.86285701 0.93967261 0.06079304]
 [0.72706173 0.36736293 0.32902674 0.9485838  0.46442562 0.0797577
  0.65550606 0.35993961 0.96892859 0.38950654]]
(3, 10)
0.2811950203147129
0.2811950203147129


In [10]:
print(nparrayRandomFloat)

# how do I access the whole second column?
# print("first column") #this is not an array --> i think it's a python list
# print(nparrayRandomFloat[:, 1]) #colon for first dimension, 1 for second dimension

# what about the whole second row?
# print("first row") #this is an array
#nparrayRandomFloat[1, :]

# what about the last two rows?
# print("last two rows")
# print(nparrayRandomFloat[-2:, :])
# print(nparrayRandomFloat[1:, :]) #this also works

# what about the first row and last two columns?
print("first row, last two columns")
print(nparrayRandomFloat[0, 8:])
# print(nparrayRandomFloat[0, -1:]) #same as above

[[0.28119502 0.95357343 0.88104884 0.10963489 0.34584754 0.50390067
  0.03466848 0.53073476 0.04075599 0.08252508]
 [0.28130629 0.06023778 0.30914082 0.06233341 0.58865027 0.04838291
  0.51969353 0.86285701 0.93967261 0.06079304]
 [0.72706173 0.36736293 0.32902674 0.9485838  0.46442562 0.0797577
  0.65550606 0.35993961 0.96892859 0.38950654]]
first row, last two columns
[0.04075599 0.08252508]


In [11]:
print(nparrayRandomFloat)

# how do I access the 1st and 3rd columns?
print("first and third columns")
print(nparrayRandomFloat[np.ix_(np.arange(nparrayRandomFloat.shape[0]), [1, 3])])
#np.ix construct open mesh for multiple sequences?
#arange is 
#0th dimension of the same
#1st and 3rd column
print(nparrayRandomFloat.shape[0])#shape function is a tuple that we can index into 
print(np.arange(nparrayRandomFloat.shape[0])) #prints integer linearly increasing in range of 3 (0,1,2)
#so all rows, and just columns 1 and 3

# whaaaat was that?

[[0.28119502 0.95357343 0.88104884 0.10963489 0.34584754 0.50390067
  0.03466848 0.53073476 0.04075599 0.08252508]
 [0.28130629 0.06023778 0.30914082 0.06233341 0.58865027 0.04838291
  0.51969353 0.86285701 0.93967261 0.06079304]
 [0.72706173 0.36736293 0.32902674 0.9485838  0.46442562 0.0797577
  0.65550606 0.35993961 0.96892859 0.38950654]]
first and third columns
[[0.95357343 0.10963489]
 [0.06023778 0.06233341]
 [0.36736293 0.9485838 ]]
3
[0 1 2]


This is where class ended

**Modifying (slices of) arrays...**

In [12]:
# how do I *change* the element at 1, 1 of the array?

In [13]:
# and now for some magic! how do I assign the second row to 1s?
nparrayRandomFloat[1] = 1
print(nparrayRandomFloat)
print(nparrayRandomFloat.dtype)

# how do I assign the second row to increasing ints?
nparrayRandomFloat[1] = np.arange(nparrayRandomFloat.shape[1])
print(nparrayRandomFloat)
print(nparrayRandomFloat.dtype)

# how do I assign the second row to 3* itself?
nparrayRandomFloat[1] *= 3
print(nparrayRandomFloat)


[[0.28119502 0.95357343 0.88104884 0.10963489 0.34584754 0.50390067
  0.03466848 0.53073476 0.04075599 0.08252508]
 [1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]
 [0.72706173 0.36736293 0.32902674 0.9485838  0.46442562 0.0797577
  0.65550606 0.35993961 0.96892859 0.38950654]]
float64
[[0.28119502 0.95357343 0.88104884 0.10963489 0.34584754 0.50390067
  0.03466848 0.53073476 0.04075599 0.08252508]
 [0.         1.         2.         3.         4.         5.
  6.         7.         8.         9.        ]
 [0.72706173 0.36736293 0.32902674 0.9485838  0.46442562 0.0797577
  0.65550606 0.35993961 0.96892859 0.38950654]]
float64
[[ 0.28119502  0.95357343  0.88104884  0.10963489  0.34584754  0.50390067
   0.03466848  0.53073476  0.04075599  0.08252508]
 [ 0.          3.          6.          9.         12.         15.
  18.         21.         24.         27.        ]
 [ 0.72706173  0.36736293  0.32902674  0.9485838   0.46442562  0.079

**Copying numpy arrays...**

In [14]:
# let's try the obvious thing
nparrayRandomFloat2 = nparrayRandomFloat
print("nparrayRandomFloat")
print(nparrayRandomFloat)
print("nparrayRandomFloat2")
print(nparrayRandomFloat2)

nparrayRandomFloat
[[ 0.28119502  0.95357343  0.88104884  0.10963489  0.34584754  0.50390067
   0.03466848  0.53073476  0.04075599  0.08252508]
 [ 0.          3.          6.          9.         12.         15.
  18.         21.         24.         27.        ]
 [ 0.72706173  0.36736293  0.32902674  0.9485838   0.46442562  0.0797577
   0.65550606  0.35993961  0.96892859  0.38950654]]
nparrayRandomFloat2
[[ 0.28119502  0.95357343  0.88104884  0.10963489  0.34584754  0.50390067
   0.03466848  0.53073476  0.04075599  0.08252508]
 [ 0.          3.          6.          9.         12.         15.
  18.         21.         24.         27.        ]
 [ 0.72706173  0.36736293  0.32902674  0.9485838   0.46442562  0.0797577
   0.65550606  0.35993961  0.96892859  0.38950654]]


In [16]:
nparrayRandomFloat2[0,0] = 0
print("nparrayRandomFloat")
print(nparrayRandomFloat)
print("nparrayRandomFloat2")
print(nparrayRandomFloat2)

# whaaat just happened??
# how do we stop that happening?? hint, what are we doing? we are *copying*
nparrayRandomFloat2 = nparrayRandomFloat.copy()

nparrayRandomFloat
[[ 0.          0.95357343  0.88104884  0.10963489  0.34584754  0.50390067
   0.03466848  0.53073476  0.04075599  0.08252508]
 [ 0.          3.          6.          9.         12.         15.
  18.         21.         24.         27.        ]
 [ 0.72706173  0.36736293  0.32902674  0.9485838   0.46442562  0.0797577
   0.65550606  0.35993961  0.96892859  0.38950654]]
nparrayRandomFloat2
[[ 0.          0.95357343  0.88104884  0.10963489  0.34584754  0.50390067
   0.03466848  0.53073476  0.04075599  0.08252508]
 [ 0.          3.          6.          9.         12.         15.
  18.         21.         24.         27.        ]
 [ 0.72706173  0.36736293  0.32902674  0.9485838   0.46442562  0.0797577
   0.65550606  0.35993961  0.96892859  0.38950654]]


**Doing other things to a whole row or column...**

In [17]:
# (review!) how do we assign value(s) to a row or column?
nparrayRandomFloat[:1] = np.zeros(nparrayRandomFloat.shape[1])
print(nparrayRandomFloat)

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          3.          6.          9.         12.         15.
  18.         21.         24.         27.        ]
 [ 0.72706173  0.36736293  0.32902674  0.9485838   0.46442562  0.0797577
   0.65550606  0.35993961  0.96892859  0.38950654]]


In [19]:
# let's sum across each column
np.sum(nparrayRandomFloat, axis=0)

# how would we sum across each row?
np.sum(nparrayRandomFloat, axis=1)


array([  0.        , 135.        ,   5.29009931])

In [23]:
# what if we had a tensor?
nptensorFloat = np.ones([3, 4, 5])
print(nptensorFloat)

np.sum(nptensorFloat, axis=2)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [25]:
# what if we don't specify an axis?
np.sum(nptensorFloat)

60.0

In [ ]:
# what other functions can we apply across axes?
# look at the docs!

In [26]:
# let's take it up a notch

nparrayRandomInt = np.random.randint(low=0, high=10, size=(3,4))
print(nparrayRandomInt)

print(nparrayRandomInt - np.min(nparrayRandomInt, axis=0))

# whaaat just happened? let's look at the shapes


[[1 2 3 5]
 [0 5 1 0]
 [6 3 9 3]]
[[1 0 2 5]
 [0 3 0 0]
 [6 1 8 3]]


In [27]:
# why is this cool?
import timeit

def sumLoop():
    '''Use for loop to sum a row vector'''
    longRow = np.array([i for i in range(1, 1000000000)])
    theSum = 0
    for i in range(len(longRow)):
        theSum += longRow[i]

def sumVectorized():
    '''Vectorized version of summing a row vector'''
    longRow = np.array([i for i in range(1, 1000000000)])
    theSum = np.sum(longRow)

print(timeit.timeit(lambda: sumLoop))
print(timeit.timeit(lambda: sumVectorized))

0.17236769999999524
0.20710589999998774


In [28]:
# what if we try to do the subtract-min thing across axis 1?
print(nparrayRandomInt - np.min(nparrayRandomInt, axis=1))


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [37]:
print(nparrayRandomInt.shape)
np.min(nparrayRandomInt, axis=1, keepdims=True).shape

(3, 4)


(3, 1)

In [36]:
# how can we fix that? make the arrays shape-compatible!
print(nparrayRandomInt - np.min(nparrayRandomInt, axis=1)[:, np.newaxis])

[[0 1 2 4]
 [0 5 1 0]
 [3 0 6 0]]


In [40]:
# is there another way to achieve this?
print(nparrayRandomInt - np.min(nparrayRandomInt, axis=1, keepdims=True))


[[0 1 2 4]
 [0 5 1 0]
 [3 0 6 0]]


Five Jupyter tips
------------------

1. To run a cell, you can hit Ctrl+Enter 
2. Quite often, a Jupyter "mistake" happens if you forget that this cell has all the memory of every cell that was already run, 
3. and only those cells, 
4. and only the last time they were run
5. To go into "select mode", hit Esc, then you can easily navigate from cell to cell

Markdown
--------

These cells that look like fancy text are in Markdown. Markdown cheat sheet: https://www.markdownguide.org/cheat-sheet