In [2]:
import numpy as np

data = np.array([2.1, 3.2, 4.3, 5.4, 6.5, 7.6, 7.8, 6.7, 5.6, 4.5, 3.4, 2.3])

In [3]:
# reverse sort
np.sort(data)[::-1]
# or np.flip(np.sort(data))
# or [creative!] -np.sort(-data)

array([7.8, 7.6, 6.7, 6.5, 5.6, 5.4, 4.5, 4.3, 3.4, 3.2, 2.3, 2.1])

In [6]:
# coerce to ints
data.astype(int)
# or np.array(data, dtype=int)

array([2, 3, 4, 5, 6, 7, 7, 6, 5, 4, 3, 2])

In [8]:
# multiply by 3
data*3
# or np.multiply(data, 3)

array([ 6.3,  9.6, 12.9, 16.2, 19.5, 22.8, 23.4, 20.1, 16.8, 13.5, 10.2,
        6.9])

In [13]:
# reverse
np.flip(data)
# or data[::-1]

array([2.3, 3.4, 4.5, 5.6, 6.7, 7.8, 7.6, 6.5, 5.4, 4.3, 3.2, 2.1])

In [11]:
# convert to a 2-d array
data.reshape(2, 6)
# or np.reshape(data, (2, 6))
# or [yes, I did forget to specify which was the long dimension!] np.reshape(data, (-1, 2))

array([[2.1, 3.2, 4.3, 5.4, 6.5, 7.6],
       [7.8, 6.7, 5.6, 4.5, 3.4, 2.3]])